def problem2():
    """
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.

    """
    seq = fib()
    x = seq.next()
    even_terms = []
    while x < 4000000:  # 4,000,000
        if x % 2 == 0:
            even_terms.append(x)
        x = seq.next()

    print sum(even_terms)


def fib():
    """
    Generator to get fib seq.

    """
    x, y = 0, 1
    while True:
        yield x
        x, y = y, x + y

if __name__ == '__main__':
    problem2()
